version: 2.1

orbs:
  node: circleci/node@4.1
  coveralls: coveralls/coveralls@1.0.6

jobs:
  build-and-test:  
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Pass tests
          command: npm run test:coverage
      - coveralls/upload
workflows:
  sample: 
    jobs:
      - build-and-test