version: 2.1

orbs:
  node: circleci/node@4.1
  coveralls: coveralls/coveralls@1.0.4

jobs:
  build-and-test:  
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Pass tests
          command: npm test

workflows:
  build: 
    jobs:
      - build-and-test:
          post-steps:
            - run:
              - coveralls/upload:
                  path_to_lcov: ./coverage/lcov.info